### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by aminya** [polysquare/cmake-forward-arguments#5]
Could you tag a new release? That would make it easier to download the library using FetchContent. Since the API has been stable, I think `v1.0.0` should be tagged

**Comment by smspillaz** [comment]
Will do!

To be honest this project is more or less unmaintained, but I can tag a release anyway.

**Comment by aminya** [comment]
It doesn't need much work. I have been using it in [project_options](https://github.com/aminya/project_options), and I will make pull requests if maintenance is needed

**Comment by smspillaz** [comment]
Done
